version: '3.7'

services:
  gateway:
    container_name: gateway_wiz_template
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
      - '5001:5001'